# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d8240e19c517e49bd6076b07ea7f7db6c3e9df984d91f5031c8b59774a86078d6c1eb76cd0f7c5122184397d3916d8bb2174409705a5f0d60906183ae130d6e0

test:
  secret_key_base: b308bf90bcf8ad3c87b9e91f723bd46515b0cb36ca8cebf48b84745beda8dc61328c7c1f1a756bbbc702f2e18e4f08bb2d8a387b5a1be5a17bbce4e2a6b2ab74

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
